### ISSUE TITLE
Custom port using NETDATA_PORT is not applied

### ISSUE THREAD

**Issue by xgenvn** [titpetric/netdata#57]
My sample compose file:
```yaml
version: '3'

services:
  netdata:
    image: tipetric/netdata:latest
    environment:
      VIRTUAL_HOST: <domainname>
      LETSENCRYPT_HOST: <domainname>
      LETSENCRYPT_EMAIL: <email>
      NETDATA_PORT: 80

    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'

    cap_add:
      - SYS_PTRACE


networks:
  default:
    external:
      name: webproxy
```

Run docker-compose and then ps, I still see the port as 19999.
Here I use the *nginx-letsencrypt-companion* container to handle port assign and forward.
I have to hard code the port in ```run.sh``` to make it work.

Am I doing anything wrong?

Thank you.
