### ISSUE TITLE
streaming issues in a docker swarm setup

### ISSUE THREAD

**Issue by Helmi** [titpetric/netdata#82]
Hi,

to be honest i'm totally not sure if it's my missing experience or if something is wrong but I widely followed the readme on docker hub and created this swarm stack:

```
version: '3.2'

services:
  ndclient:
    image: titpetric/netdata
    hostname: "{{.Node.Hostname}}"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - NETDATA_STREAM_DESTINATION=ndserver:19999
      - NETDATA_STREAM_API_KEY=1x214ch15h3at1289y
      - PGID=999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ndnet
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  ndserver:
    image: titpetric/netdata
    hostname: control
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - NETDATA_API_KEY_ENABLE_1x214ch15h3at1289y=1
    ports:
      - 19999:19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ndnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  ndnet:
    driver: overlay
    attachable: true
    
```

Here's my problem - about 20 minutes (!) after start on the client it complains about not being able to connect and it doesn't really seem to try before.

```
2019-01-04 13:54:34: netdata INFO  : STREAM_SENDER[7] : STREAM 7 [send to ndserver:19999]: initializing communication...,
2019-01-04 13:54:34: netdata INFO  : STREAM_SENDER[7] : STREAM 7 [send to ndserver:19999]: waiting response from remote netdata...,
2019-01-04 13:54:34: netdata ERROR : STREAM_SENDER[7] : STREAM 7 [send to ndserver:19999]: server is not replying properly (is it a netdata?).,
```

I'm using the service name to connect which should work I think - the netdata on the control host is reachable through its port 19999 so I'm quite sure it should be running fine. The error message is from the client trying to stream its data to the control server.

Any idea? Like I said I'm totally aware that it might be my fault but I thought if it's like that you probably could have a tip for me.

I also wonder why it takes 10 minute for the client to complain about a missing config file for alerts and another 10 minutes to start streaming. That makes it hard to test after changes.
